added getters for trailer variables in DAPHNEFrame
DUNE-DAQ/fddetdataformats pull request #27
Opened 2024-08-10 10:46 UTC by denisecasazza

2024-08-14 12:11 UTC, alessandrothea commented
Am I mistake or this PR is not just adding getters, but also changes the DAPHNE v2 data format?
If that is the case, the new format needs to be presented and discussed before this PR can be merged.

2024-08-14 12:12 UTC, alessandrothea requested changes
Clairfy changes to trailer bitfields and payload size

2024-08-19 10:22 UTC, alessandrothea commented
I am mistaken, there is no change in the payload side, but the new bit arrangement must be documented.

2025-03-11 14:37 UTC, closed without merging

2025-03-11 14:37 UTC, wesketchum commented
Closing in favor of the work on the v5 line for PDS TPs. Can create additional PRs there if needed.